baseurl = "https://tadaa-data.de"
languageCode = "en-us"
title = "Tadaa, Data!"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "â†©"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/post/:year/:month/:slug"

[taxonomies]
    tag = "tags"
    category = "categories"
    package = "packages"

[params]
    # Tell me who you are
    author = "Tadaa, Data!"
    bio = "Throwing code at data and seeing what sticks"
    location = "Bremen, Germany"
    site_description = ""
    copyright  = " and [blogdown](https://github.com/rstudio/blogdown). Theme by [PPOffice](http://github.com/ppoffice)"
    avatar = "tadaa_sq.png"
    logo = "tadaa_sq.png"
    disable_mathjax = false

    piwikID = 1
    piwikURL = "https://analytics.tadaa-data.de/"

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	  custom_css = []
	  custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tadaa, R-Intro!"
    link   = "https://r-intro.tadaa-data.de/"
    icon   = "fa fa-book"

[[params.menu]]
    before = false
    label  = "R-Bloggers"
    link   = "https://www.r-bloggers.com/"
    icon   = "fab fa-r-project"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.

# See styles.css#727 for cell width, which depends on the number of links used
    github          = "tadaadata"
    youtube         = ""
    vimeo           = ""
    tumblr          = ""
    slideshare      = ""
    facebook        = "tadaadata"
    twitter         = "tadaa_data"
    mail            = "mail@tadaa-data.de"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = true
    tags = true
    tag_cloud = false
    packages = true
