title = "Tadaa, Data!"
baseURL = "https://tadaa-data.de"
languageCode = "en-us"
theme = "ananke"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/tadaa_sq.png"
  description = "Throwing code at data to see what sticks"
  facebook = ""
  twitter = "https://twitter.com/tadaa_data"
  instagram = ""
  youtube = ""
  github = "https://github.com/tadaadata"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-silver"
  featured_image = "/images/emptyplot_wide.png"
  recent_posts_number = 2
  custom_css = ["css/tadaa.css"]